use phf::{phf_set, Set};

static RESERVED_KW: Set<&'static str> = phf_set! {
    "abstype",
    "and",
    "andalso",
    "as",
    "case",
    "datatype",
    "do",
    "else",
    "end",
    "exception",
    "fn",
    "fun",
    "handle",
    "if",
    "in",
    "infix",
    "infixr",
    "let",
    "local",
    "nonfix",
    "of",
    "op",
    "open",
    "orelse",
    "raise",
    "rec",
    "then",
    "type",
    "val",
    "with",
    "withtype",
    "while",
    "eqtype",
    "functor",
    "include",
    "sharing",
    "sig",
    "signature",
    "struct",
    "structure",
    "where",
    "(", ")", "[", "]", "{", "}", ",", ":", ";",
    "...", "_", "|", "=", "=>", "->", "#", ":>"
};

pub fn is_keyword(s: &str) -> bool {
    RESERVED_KW.contains(s)
}
